### ISSUE TITLE
Peer-to-peer code review

### ISSUE THREAD

**Issue by over-geek** [ahmedeid6842/API_Capstone#36]
### HIGHLIGHTS
- Great job working with the API
- Good-looking interface

## 👀 Suggestions
- Kindly consider separating functions that manipulate the DOM from those that access data
- Kindly consider adding a link to your demo link section to your table of contents in the README.md file

**Comment by ahmedeid6842** [comment]
Thanks @over-geek for your time and effort to review my code :pray:
